### ISSUE TITLE
Job runs a second time without arguments and fails

### ISSUE THREAD

**Issue by bubbaspaarx** [salsify/delayed_job_groups_plugin#23]
We have a small jobs group running and it appears to work initially. It runs the first job which takes 3 arguments without issue. This job completes and is removed as a job. It then checks the job group for more jobs and finds the same job but now without arguments which obviously then fails. Can't seem to work out why this would happen.

Our code

```
job_group = Delayed::JobGroups::JobGroup.create!(
  on_completion_job: MyJob.new(arg1, arg2),
  on_completion_job_options: { queue: :fast }
)

job_group.enqueue(MyNextJob.new(arg1, arg2, arg3), queue: :fast)
job_group.enqueue(MyNextNextJob.new(arg1, arg2), queue: :fast)
job_group.mark_queueing_complete
```

**Comment by bubbaspaarx** [comment]
We are using delayed_job_active_record gem. Could this be the problem?

**Comment by jturkel** [comment]
This gem is compatible with delayed_job_active_record (in fact it assumes the ActiveRecord backend for delayed_job) so that isn't the problem. Just to make sure I understand the issue, `MyNextJob.new(arg1, arg2, arg3)` runs successfully but then the worker attempts to run `MyNextJob.new` which fails due to the missing arguments? Can you inspect the state of the `delayed_jobs` table (ignoring any failed jobs) after enqueueing the jobs but before running any to confirm it has the expected state?

**Comment by bubbaspaarx** [comment]
We worked out the issue here. It looks we had migrated existing jobs into the jobs_group where they already had a 'perform_now' on them. This meant the jobs ran before the jobs group ran and meant they had already been run by the time this happened. Error on our part.

**Comment by jturkel** [comment]
Glad you figured out the problem @bubbaspaarx. Thanks for updating the issue.
